# docker-compose.yml
version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nextjs_app
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_OPENAI_API_KEY=${NEXT_PUBLIC_OPENAI_API_KEY}
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
        depends_on:
            - db
        volumes:
            - ./src:/usr/src/app/src
            - ./public:/usr/src/app/public
            - ./app:/usr/src/app/app
            - ./components:/usr/src/app/components
            - ./lib:/usr/src/app/lib
            - ./styles:/usr/src/app/styles
            - ./utils:/usr/src/app/utils
            - ./hooks:/usr/src/app/hooks
            - ./next.config.mjs:/usr/src/app/next.config.mjs
            - /usr/src/app/node_modules

    db:
        image: postgres:15-alpine
        container_name: postgres_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: mydatabase
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
    postgres_data:
