services:
    # Next.js Application Service
    nextjs-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: interviewedge_app
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - QDRANT_URL=http://qdrant_db:6333
        volumes:
            - .:/usr/src/app # Fixed: Match the WORKDIR in Dockerfile
            - /usr/src/app/node_modules # Prevent overwriting node_modules
            - /usr/src/app/.next # Persist Next.js cache
        depends_on:
            - qdrant_db
        restart: unless-stopped

    # Qdrant Vector Database Service
    qdrant_db:
        image: qdrant/qdrant:v1.14.1
        container_name: qdrant_vector_db
        ports:
            - '6333:6333' # HTTP API
            - '6334:6334' # gRPC (optional)
        volumes:
            - qdrant_storage:/qdrant/storage
        environment:
            - QDRANT__LOG_LEVEL=INFO
        restart: unless-stopped

volumes:
    qdrant_storage:
