-- -- init-db.sql
-- CREATE TABLE IF NOT EXISTS files (
--     id SERIAL PRIMARY KEY,
--     file_id VARCHAR(255) NOT NULL,
--     name VARCHAR(255),
--     description TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- CREATE TABLE IF NOT EXISTS assistants (
--     id VARCHAR(255) PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     instructions TEXT,
--     role_description TEXT,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );